Repository SEKOIA-IO/documentation, pull requests merged in 2022-11, with the labels that each got.

#622 GatWatcher: add AIONIQ documentation
  docs/xdr/features/collect/integrations/network/gatewatcher_aioniq.md
  mkdocs.yml
Labels: documentation

#623 Gatewatcher: fix typo
  docs/xdr/features/collect/integrations/network/gatewatcher_aioniq.md
  mkdocs.yml
Labels: bug

#626 Tehtris: add documentation
  docs/xdr/features/collect/integrations/endpoint/tehtris_edr.md
  mkdocs.yml
Labels: enhancement

#640 Update crowdstrike_falcon.md
  docs/xdr/features/collect/integrations/endpoint/crowdstrike_falcon.md
Labels: documentation

#670 Okta: add documentation
  docs/xdr/features/collect/integrations/cloud_and_saas/okta_system_log.md
  mkdocs.yml
Labels: documentation, enhancement
