Repository SEKOIA-IO/documentation, pull requests merged in 2022-07, with the labels that each got.

#330 AWS: documentation about S3 for logs
  _shared_content/automate/library/aws.md
  docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_s3_logs.md
  mkdocs.yml
Labels: documentation

#332 Documents the telemetry of an observable
  _shared_content/intelligence_center/consume/observables.md
Labels: enhancement

#334 HTTPSCollector: add section about the plain endpoints
  docs/xdr/features/collect/ingestion_methods/https.md
Labels: documentation

#336 ProofPoint: add the documentation for TAP
  _shared_content/operations_center/integrations/generated/proofpoint-tap_do_not_edit_manually.md
  docs/xdr/features/collect/integrations/email/proofpoint_tap.md
  mkdocs.yml
Labels: documentation, enhancement

#358 Http Ingestion: add the HTTP Basic Auth
  docs/xdr/features/collect/ingestion_methods/https.md
Labels: documentation

#360 HTTPIngestion: /jsons and reorganization
  docs/xdr/features/collect/ingestion_methods/https.md
Labels: documentation, enhancement

#361 HTTPIngestion: add some missing informations
  docs/xdr/features/collect/ingestion_methods/https.md
Labels: bug, documentation

#368 Initializes the Raw Event Format
  docs/xdr/features/collect/integrations/generic/raw.md
Labels: enhancement

#372 explicit the event search limit
  docs/xdr/features/investigate/events.md
Labels: enhancement
