Repository SEKOIA-IO/documentation, pull requests merged in 2022-10, with the labels that each got.

#532 Display suggested rules on all supported integrations
  docs/xdr/features/collect/integrations/application/alsid.md
  docs/xdr/features/collect/integrations/application/apache.md
  docs/xdr/features/collect/integrations/application/bind.md
  docs/xdr/features/collect/integrations/application/dhcpd.md
  docs/xdr/features/collect/integrations/application/haproxy.md
  docs/xdr/features/collect/integrations/application/nginx.md
  docs/xdr/features/collect/integrations/application/openssh.md
  docs/xdr/features/collect/integrations/application/sekoiaio_activity_logs.md
  docs/xdr/features/collect/integrations/application/thehive.md
  docs/xdr/features/collect/integrations/application/unbound.md
  docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_cloudtrail.md
  docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_flow_logs.md
  docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_s3_logs.md
  docs/xdr/features/collect/integrations/cloud_and_saas/azure/azure_ad.md
  docs/xdr/features/collect/integrations/cloud_and_saas/azure/azure_front_door.md
  docs/xdr/features/collect/integrations/cloud_and_saas/azure/azure_linux.md
  docs/xdr/features/collect/integrations/cloud_and_saas/azure/azure_mysql.md
  docs/xdr/features/collect/integrations/cloud_and_saas/azure/azure_network_watcher.md
  docs/xdr/features/collect/integrations/cloud_and_saas/azure/azure_windows.md
  docs/xdr/features/collect/integrations/cloud_and_saas/cisco_umbrella/umbrella_dns.md
  docs/xdr/features/collect/integrations/cloud_and_saas/digital_shadows.md
  docs/xdr/features/collect/integrations/cloud_and_saas/imperva_waf.md
  docs/xdr/features/collect/integrations/cloud_and_saas/office365/message_trace.md
  docs/xdr/features/collect/integrations/cloud_and_saas/office365/o365.md
  docs/xdr/features/collect/integrations/email/fortimail.md
  docs/xdr/features/collect/integrations/email/postfix.md
  docs/xdr/features/collect/integrations/email/proofpoint_pod.md
  docs/xdr/features/collect/integrations/email/proofpoint_tap.md
  docs/xdr/features/collect/integrations/email/spamassassin.md
  docs/xdr/features/collect/integrations/email/vade.md
  docs/xdr/features/collect/integrations/endpoint/microsoft_defender_for_endpoints.md
  docs/xdr/features/collect/integrations/endpoint/tanium.md
  docs/xdr/features/collect/integrations/generic/cef.md
  docs/xdr/features/collect/integrations/network/checkpoint.md
  docs/xdr/features/collect/integrations/network/cisco_asa.md
  docs/xdr/features/collect/integrations/network/f5-big-ip.md
  docs/xdr/features/collect/integrations/network/forcepoint_web_gateway.md
  docs/xdr/features/collect/integrations/network/fortigate.md
  docs/xdr/features/collect/integrations/network/fortiproxy.md
  docs/xdr/features/collect/integrations/network/fortiweb.md
  docs/xdr/features/collect/integrations/network/infoblox_ddi.md
  docs/xdr/features/collect/integrations/network/netfilter.md
  docs/xdr/features/collect/integrations/network/paloalto.md
  docs/xdr/features/collect/integrations/network/pulse.md
  docs/xdr/features/collect/integrations/network/skyhigh_secure_web_gateway.md
  docs/xdr/features/collect/integrations/network/sophos_fw.md
  docs/xdr/features/collect/integrations/network/squid.md
  docs/xdr/features/collect/integrations/network/stormshield_network_security.md
  docs/xdr/features/collect/integrations/network/suricata.md
  docs/xdr/features/collect/integrations/network/vectra.md
  docs/xdr/features/collect/integrations/network/wallix.md
  docs/xdr/features/collect/integrations/network/zeek.md
Labels: documentation

#549 MicrosoftAlwaysOnVPN: add documentation
  docs/xdr/features/collect/integrations/network/microsoft_always_on_vpn.md
  mkdocs.yml
Labels: enhancement

#590 WatchGuard: add Firebox documentation
  docs/xdr/features/collect/integrations/network/watchguard_firebox.md
  mkdocs.yml
Labels: documentation

#592 typo in an installation command for linuw
  docs/xdr/features/collect/integrations/endpoint/sekoiaio.md
Labels: documentation

#576 Update CTI index
  docs/cti/index.md
Labels: DONOTMERGE
