Repository SEKOIA-IO/documentation, pull requests merged in 2022-12, with the labels that each got.

#680 Cybereason: add new integration
  docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
  docs/xdr/features/collect/integrations/endpoint/cybereason_malop_activity.md
  mkdocs.yml
Labels: enhancement

#684 Cybereason: add beta flag for the new format
  docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
Labels: enhancement

#686 Cybereason: add warning
  docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
Labels: bug

#688 AWS: fix WAF documentation
  docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_waf.md
Labels: enhancement

#703 Office365: document Microsoft Defender for 0365
  docs/xdr/features/collect/integrations/cloud_and_saas/office365/o365.md
  mkdocs.yml
Labels: enhancement

#711 CEF: fix the link to the specification
  docs/xdr/features/collect/integrations/generic/cef.md
Labels: bug

#698 AWS: update the AWS VPC flow logs documentation
  docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_flow_logs.md
Labels: bug, documentation

#712 Cybereason: fix the link to the Cybereason symphony module
  docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
Labels: bug

#725 OKTA: update the documentation
  docs/xdr/features/collect/integrations/cloud_and_saas/okta_system_log.md
  mkdocs.yml
Labels: documentation, enhancement

#630 docs(aws-gateway): add endpoint documentation for API
  docs/cti/develop/rest_api/edl-gateway.md
  mkdocs.yml
Labels: documentation
