Repository SEKOIA-IO/documentation, pull requests merged in 2022-03, with the labels that each got.

#211 Create vade for M365 documentation
  docs/operation_center/integration_catalog/email/vade.md
  mkdocs.yml
Labels: documentation

#217 reference WELF in the documentation of Pulse
  docs/operation_center/integration_catalog/network/pulse.md
Labels: enhancement

#229 feat(symhpony): update library doc
  docs/assets/playbooks/library/digital-shadows.png
  docs/assets/playbooks/library/the-hive.png
  docs/playbooks/library/aws.md
  docs/playbooks/library/binaryedge-s-api.md
  docs/playbooks/library/censys.md
  docs/playbooks/library/digital-shadows.md
  docs/playbooks/library/fortigate-fw.md
  docs/playbooks/library/iknowwhatyoudownload.md
  docs/playbooks/library/mattermost.md
  docs/playbooks/library/onyphe.md
  docs/playbooks/library/riskiq.md
  docs/playbooks/library/rss.md
  docs/playbooks/library/sekoia-io.md
  docs/playbooks/library/shodan.md
  docs/playbooks/library/stix.md
  docs/playbooks/library/the-hive.md
  docs/playbooks/library/vade-secure.md
  docs/playbooks/library/virustotal.md
  mkdocs.yml
Labels: documentation, enhancement

#230 Integrations: update the documentation of AWS integrations
  docs/operation_center/integration_catalog/cloud_and_saas/aws/aws_cloudtrail.md
  docs/operation_center/integration_catalog/cloud_and_saas/aws/aws_flow_logs.md
Labels: documentation

#226 feat: rework rules catalog page and add correlation
  docs/assets/operation_center/rules_catalog/auto_enable.png
  docs/assets/operation_center/rules_catalog/available_verified.png
  docs/assets/operation_center/rules_catalog/capabilities.png
  docs/assets/operation_center/rules_catalog/custom_rule.png
  docs/assets/operation_center/rules_catalog/effort_level.png
  docs/assets/operation_center/rules_catalog/limit_scope.png
  docs/assets/operation_center/rules_catalog/rule_details.png
  docs/assets/operation_center/rules_catalog/rules_catalog.png
  docs/assets/operation_center/rules_catalog/security_profile.png
  docs/operation_center/rules_catalog.md
Labels: documentation

#234 Update rsyslog.md
  docs/operation_center/data_collection/ingestion_methods/rsyslog.md
Labels: documentation, sales_request

#248 Rules Catalog: add new Sigma modifiers
  docs/operation_center/rules_catalog.md
Labels: documentation
