Repository SEKOIA-IO/documentation, pull requests merged in 2022-09, with the labels that each got.

#461 Symantec: add Symantec EPP integration
  docs/xdr/features/collect/integrations/endpoint/symantec_epp.md
  mkdocs.yml
Labels: documentation

#465 SophosEDR: fix link to trigger documentation
  docs/xdr/features/collect/integrations/endpoint/sophos_edr.md
Labels: bug

#432 Office365: refactor the prerequisites
  docs/xdr/features/collect/integrations/cloud_and_saas/office365/o365.md
  docs/xdr/features/collect/integrations/cloud_and_saas/office365/o365_appendix.md
  mkdocs.yml
Labels: documentation, enhancement

#470 AzureFrontDoor: add documentation
  docs/xdr/features/collect/integrations/cloud_and_saas/azure/azure_front_door.md
  mkdocs.yml
Labels: documentation, enhancement

#485 Introduce Cisco WSA doc
  docs/xdr/features/collect/integrations/network/cisco_wsa.md
  mkdocs.yml
Labels: documentation, enhancement

#497 doc(Office365/MessageTrace): Add doc for OAuth.
  docs/xdr/features/collect/integrations/cloud_and_saas/office365/message_trace.md
Labels: documentation, enhancement

#515 docs built in rules
  docs/xdr/features/detect/built_in_detection_rules.md
  mkdocs.yml
Labels: documentation

#526 documentation(Office365/MessageTrace): Add `start_time` documentation.
  docs/xdr/features/collect/integrations/cloud_and_saas/office365/message_trace.md
Labels: documentation, enhancement

#528 Proofpoint: add documentation for ProofPoint PoD
  docs/xdr/features/collect/integrations/email/proofpoint_pod.md
  mkdocs.yml
Labels: enhancement
