Repository SEKOIA-IO/documentation, pull requests merged in 2023-02, with the labels that each got.

#849 PaloAltoXSOAR: fix dead link
  _shared_content/intelligence_center/integrations/paloalto_xsoar.md
Labels: bug

#852 Add OpenID Configuration documentation [Override]
  docs/assets/getting_started/SSO_Authentication.png
  docs/assets/getting_started/SSO_JIT.png
  docs/assets/getting_started/SSO_URL.png
  docs/assets/getting_started/SSO_identity.png
  docs/getting_started/SSO_openid_connect.md
  mkdocs.yml
Labels: documentation

#843 doc(google-cloud): specify required role for sink creation
  _shared_content/operations_center/integrations/google_cloud.md
Labels: documentation, enhancement

#848 Cybereason: add rights
  docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
Labels: bug

#853 FreeRADIUS: add doc
  docs/xdr/features/collect/integrations/application/freeradius.md
  mkdocs.yml
Labels: documentation

#847 FortiSOAR: add documentation
  docs/xdr/features/integrations/fortisoar.md
  mkdocs.yml
Labels: enhancement

#873 Fix Sonicwall documentation
  docs/xdr/features/collect/integrations/network/sonicwall_fw.md
Labels: enhancement

#874 Add doc on ioc collections in CTI & TIP
  _shared_content/intelligence_center/consume/ioccollections.md
  _shared_content/ioccollections.md
  docs/xdr/features/detect/ioccollections.md
  mkdocs.yml
Labels: enhancement

#889 Linux: deprecate format
  docs/xdr/features/collect/integrations/endpoint/linux.md
Labels: enhancement

#888 Freeradius: Out of Beta
  docs/xdr/features/collect/integrations/application/freeradius.md
Labels: enhancement

#890 Cybereason: Add note about IP filtering on Cybereason's instances
  docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
Labels: enhancement

#901 PaloAlto: Explain how to forward logs through CDL
  docs/xdr/features/collect/integrations/network/paloalto.md
Labels: documentation, enhancement
