Repository SEKOIA-IO/documentation, pull requests merged in 2023-07, with the labels that each got.

#1179 Script: make update_mkdocs more resilient against empty taxonomy
  _shared_content/operations_center/integrations/generated/250e4095-fa08-4101-bb02-e72f870fcbd1.md
  _shared_content/operations_center/integrations/generated/2b13307b-7439-4973-900a-2b58303cac90.md
  _shared_content/operations_center/integrations/generated/302065ea-0491-41cf-a472-09b59799c55d.md
  _shared_content/operations_center/integrations/generated/3c7057d3-4689-4fae-8033-6f1f887a70f2.md
  _shared_content/operations_center/integrations/generated/3e060900-4004-4754-a597-d2944a601930.md
  _shared_content/operations_center/integrations/generated/40deb162-6bb1-4635-9c99-5c2de7e1d340.md
  _shared_content/operations_center/integrations/generated/6b8cb346-6605-4240-ac15-3828627ba899.md
  _shared_content/operations_center/integrations/generated/8a9894f8-d7bc-4c06-b96a-8808b3c6cade.md
  _shared_content/operations_center/integrations/generated/98fa7079-41ae-4033-a93f-bbd70d114188.md
  _shared_content/operations_center/integrations/generated/99da26fc-bf7b-4e5b-a76c-408472fcfebb.md
  _shared_content/operations_center/integrations/generated/bf8867ee-43b7-444c-9475-a7f43754ab6d.md
  _shared_content/operations_center/integrations/generated/c10307ea-5dd1-45c6-85aa-2a6a900df99b.md
  _shared_content/operations_center/integrations/generated/ccf942fe-c839-42be-a081-5c3f946e80f5.md
  _shared_content/operations_center/integrations/generated/d2725f97-0c7b-4942-a847-983f38efb8ff.md
  _shared_content/operations_center/integrations/generated/e4a758fc-7620-49e6-b8ed-b7fb3d7fa232.md
  scripts/update_mkdocs/update_mkdocs.py
Labels: bug

#1186 add prerequisites
  _shared_content/operations_center/integrations/aws_create_sqs_queue.md
Labels: documentation

#1184 CrowdStrike Telemetry: add beta flag
  docs/xdr/features/collect/integrations/endpoint/crowdstrike_telemetry.md
Labels: bug

#1196 HTTP Ingestion method: add examples with the intake key in the query string
  docs/xdr/features/collect/ingestion_methods/https.md
Labels: enhancement

#1214 VMWare: add documentation about VCenter
  docs/xdr/features/collect/integrations/endpoint/vmware/vmware_vcenter.md
  mkdocs.yml
Labels: documentation

#1217 Chore: rename section
  docs/xdr/features/collect/integrations/application/apache.md
  docs/xdr/features/collect/integrations/application/freeradius.md
  docs/xdr/features/collect/integrations/application/rsa_securid.md
  docs/xdr/features/collect/integrations/cloud_and_saas/sophos_threat_analysis_center.md
  docs/xdr/features/collect/integrations/cloud_and_saas/ubika_waap.md
  docs/xdr/features/collect/integrations/email/cisco_esa.md
  docs/xdr/features/collect/integrations/email/fortimail.md
  docs/xdr/features/collect/integrations/endpoint/auditbeat_linux.md
  docs/xdr/features/collect/integrations/endpoint/symantec_epp.md
  docs/xdr/features/collect/integrations/endpoint/trend_micro_deep_security.md
  docs/xdr/features/collect/integrations/endpoint/vmware/vmware_esxi.md
  docs/xdr/features/collect/integrations/endpoint/vmware/vmware_vcenter.md
  docs/xdr/features/collect/integrations/endpoint/winlogbeat.md
  docs/xdr/features/collect/integrations/network/cisco/cisco_asa.md
  docs/xdr/features/collect/integrations/network/cisco/cisco_ios.md
  docs/xdr/features/collect/integrations/network/cisco/cisco_ise.md
  docs/xdr/features/collect/integrations/network/cisco/cisco_meraki_mx.md
  docs/xdr/features/collect/integrations/network/cisco/cisco_nx_os.md
  docs/xdr/features/collect/integrations/network/cisco/cisco_wsa.md
  docs/xdr/features/collect/integrations/network/citrix_adc.md
  docs/xdr/features/collect/integrations/network/forcepoint_web_gateway.md
  docs/xdr/features/collect/integrations/network/fortigate.md
  docs/xdr/features/collect/integrations/network/fortiproxy.md
  docs/xdr/features/collect/integrations/network/fortiweb.md
  docs/xdr/features/collect/integrations/network/gatewatcher_aioniq.md
  docs/xdr/features/collect/integrations/network/infoblox_ddi.md
  docs/xdr/features/collect/integrations/network/microsoft_always_on_vpn.md
  docs/xdr/features/collect/integrations/network/opnsense.md
  docs/xdr/features/collect/integrations/network/paloalto.md
  docs/xdr/features/collect/integrations/network/pfsense.md
  docs/xdr/features/collect/integrations/network/sonicwall_fw.md
  docs/xdr/features/collect/integrations/network/sophos_fw.md
  docs/xdr/features/collect/integrations/network/varonis_data_security.md
  docs/xdr/features/collect/integrations/network/watchguard_firebox.md
Labels: enhancement

#1216 VMware: reword the description of vcenter
  docs/xdr/features/collect/integrations/endpoint/vmware/vmware_vcenter.md
Labels: documentation
