Repository SEKOIA-IO/documentation, pull requests merged in 2023-05, with the labels that each got.

#1051 VMware: add documentation about ESXi
  docs/xdr/features/collect/integrations/endpoint/vmware/vmware_esxi.md
  mkdocs.yml
Labels: enhancement

#1052 Documentation for WithSecure Elements Intake
  docs/assets/operation_center/integration_catalog/endpoint/withsecure/withsecure_create_api_client.png
  docs/assets/operation_center/integration_catalog/endpoint/withsecure/withsecure_playbook_collect.png
  docs/xdr/features/collect/integrations/endpoint/withsecure_elements.md
  mkdocs.yml
Labels: enhancement

#1056 RSA: add documentation
  docs/xdr/features/collect/integrations/application/rsa_securid.md
  mkdocs.yml
Labels: enhancement

#1058 RSA: fix typo in the title
  mkdocs.yml
Labels: bug

#1063 Formats: Out of beta
  docs/xdr/features/collect/integrations/endpoint/winlogbeat.md
  docs/xdr/features/collect/integrations/network/cisco/cisco_meraki_mx.md
Labels: documentation, enhancement
