Repository SEKOIA-IO/documentation, pull requests merged in 2023-06, with the labels that each got.

#1100 Citrix: update the inclusion of autogenerated documentation
  docs/xdr/features/collect/integrations/network/citrix_adc.md
Labels: bug

#1105 OGO: fix the name of the format in the menu
  mkdocs.yml
Labels: bug

#1113 Github: add beta mention
  docs/xdr/features/collect/integrations/cloud_and_saas/github_audit_logs.md
Labels: enhancement

#1140 Cloudflare: add the beta mention in the documentation
  docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-access-requests.md
  docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-audit-logs.md
  docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-dns.md
  docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-http.md
  docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-network.md
Labels: enhancement

#1132 Update github_audit_logs.md
  docs/xdr/features/collect/integrations/cloud_and_saas/github_audit_logs.md
Labels: documentation

#1143 Cisco: add Cisco ISE in the menu
  mkdocs.yml
Labels: bug
