Repository SEKOIA-IO/documentation, pull requests merged in 2023-09, with the labels that each got.

#1248 New version of the Telemetry documentation
  _shared_content/intelligence_center/consume/observables.md
  _shared_content/intelligence_center/consume/telemetry.md
  docs/assets/intelligence_center/telemetry/object-telemetry-types.png
  docs/assets/intelligence_center/telemetry/observable-telemetry-types.png
  docs/assets/intelligence_center/telemetry/telemetry-alerts.png
  docs/assets/intelligence_center/telemetry/telemetry-heatmap-object.png
  docs/assets/intelligence_center/telemetry/telemetry-heatmap.png
  docs/assets/intelligence_center/telemetry/telemetry-observable.png
  mkdocs.yml
Labels: enhancement

#1298 Google: Update the doc
  docs/xdr/features/collect/integrations/cloud_and_saas/google/google_cloud_audit.md
  docs/xdr/features/collect/integrations/cloud_and_saas/google/google_reports.md
  mkdocs.yml
Labels: enhancement

#1299 Google: fix Google Report docs
  docs/xdr/features/collect/integrations/cloud_and_saas/google/google_reports.md
Labels: bug

#1203 Format: add a guide
  _shared_content/develop/guides/formats/create_a_format.md
  _shared_content/develop/guides/formats/datasources.md
  _shared_content/develop/guides/formats/overview.md
  _shared_content/develop/guides/formats/parser.md
  _shared_content/develop/guides/formats/smartdescriptions.md
  _shared_content/develop/guides/formats/structured_event.md
  _shared_content/develop/guides/formats/taxonomy.md
  mkdocs.yml
Labels: documentation

#1312 Trend Micro Apex One
  docs/xdr/features/collect/integrations/endpoint/trend_micro/trend_micro_apex_one.md
  docs/xdr/features/collect/integrations/endpoint/trend_micro/trend_micro_deep_security.md
  mkdocs.yml
Labels: enhancement

#1313 Trend Micro: add redirection
  mkdocs.yml
Labels: bug

#1314 Beta: change the message for beta integrations
  docs/xdr/features/collect/integrations/application/rsa_securid.md
  docs/xdr/features/collect/integrations/cloud_and_saas/aws/aws_guardduty.md
  docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-access-requests.md
  docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-audit-logs.md
  docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-dns.md
  docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-http.md
  docs/xdr/features/collect/integrations/cloud_and_saas/cloudflare/cloudflare-gateway-network.md
  docs/xdr/features/collect/integrations/cloud_and_saas/duo_security.md
  docs/xdr/features/collect/integrations/cloud_and_saas/github_audit_logs.md
  docs/xdr/features/collect/integrations/cloud_and_saas/ogo_shield.md
  docs/xdr/features/collect/integrations/cloud_and_saas/salesforce.md
  docs/xdr/features/collect/integrations/cloud_and_saas/sophos_threat_analysis_center.md
  docs/xdr/features/collect/integrations/cloud_and_saas/ubika_waap.md
  docs/xdr/features/collect/integrations/email/cisco_esa.md
  docs/xdr/features/collect/integrations/endpoint/crowdstrike_telemetry.md
  docs/xdr/features/collect/integrations/endpoint/darktrace_threat_visualizer.md
  docs/xdr/features/collect/integrations/endpoint/sentinelone_cloudfunnel2.0.md
  docs/xdr/features/collect/integrations/endpoint/trellix_epo.md
  docs/xdr/features/collect/integrations/endpoint/trend_micro/trend_micro_apex_one.md
  docs/xdr/features/collect/integrations/endpoint/vmware/vmware_esxi.md
  docs/xdr/features/collect/integrations/endpoint/vmware/vmware_vcenter.md
  docs/xdr/features/collect/integrations/network/cisco/cisco_nx_os.md
  docs/xdr/features/collect/integrations/network/citrix_adc.md
  docs/xdr/features/collect/integrations/network/sonicwall_fw.md
  docs/xdr/features/collect/integrations/network/varonis_data_security.md
Labels: enhancement

#1323 Google: add the scopes required for the integration
  docs/xdr/features/collect/integrations/cloud_and_saas/google/google_reports.md
Labels: enhancement

#1324 Google: fix layout
  docs/xdr/features/collect/integrations/cloud_and_saas/google/google_reports.md
Labels: bug

#1325 Cato: add beta notice
  docs/xdr/features/collect/integrations/cloud_and_saas/cato_sase.md
Labels: bug

#1342 StormShield SES documentation
  docs/assets/operation_center/integration_catalog/endpoint/stormshield/stormshield_ses_01.png
  docs/assets/operation_center/integration_catalog/endpoint/stormshield/stormshield_ses_02.png
  docs/assets/operation_center/integration_catalog/endpoint/stormshield/stormshield_ses_03.png
  docs/xdr/features/collect/integrations/endpoint/stormshield_endpoint.md
  mkdocs.yml
Labels: documentation

#1344 Zscaler: add documentation about Zscaler Internet Access
  docs/assets/operation_center/integration_catalog/cloud_and_saas/zscaler/zia_cloud.png
  docs/assets/operation_center/integration_catalog/cloud_and_saas/zscaler/zia_formatting.png
  docs/assets/operation_center/integration_catalog/cloud_and_saas/zscaler/zia_general_firewall.png
  docs/assets/operation_center/integration_catalog/cloud_and_saas/zscaler/zia_general_web.png
  docs/assets/operation_center/integration_catalog/cloud_and_saas/zscaler/zia_menu.png
  docs/assets/operation_center/integration_catalog/cloud_and_saas/zscaler/zia_nss_feeds.png
  docs/assets/operation_center/integration_catalog/cloud_and_saas/zscaler/zia_siem_connectvity.png
  docs/xdr/features/collect/integrations/cloud_and_saas/zscaler_zia.md
  mkdocs.yml
Labels: enhancement

#1355 Zscaler: fix the name of the asset
  docs/assets/operation_center/integration_catalog/cloud_and_saas/zscaler/zia_siem_connectivity.png
  docs/xdr/features/collect/integrations/cloud_and_saas/zscaler_zia.md
Labels: bug

#1349 FAQ: add accepted representations of datetime in the events
  docs/xdr/FAQ/datetime.md
  docs/xdr/features/collect/ingestion_methods/index.md
  mkdocs.yml
Labels: enhancement

#1356 Zscaler: fix the HTTP endpoint to use for Cloud NSS
  docs/xdr/features/collect/integrations/cloud_and_saas/zscaler_zia.md
Labels: bug
