Repository SEKOIA-IO/documentation, pull requests merged in 2023-03, with the labels that each got.

#912 Cybereason: Out of Beta
  docs/xdr/features/collect/integrations/endpoint/cybereason_malop.md
Labels: bug

#924 Postfix: fix the autogenerated postfix documentation
  docs/xdr/features/collect/integrations/email/postfix.md
Labels: bug

#955 Cisco: Add the documentation about Cisco IOS
  docs/xdr/features/collect/integrations/network/cisco/cisco_ios.md
  mkdocs.yml
Labels: documentation

#956 Cisco: fix Cisco Web Security Appliance
  docs/xdr/features/collect/integrations/network/cisco/cisco_wsa.md
Labels: documentation, enhancement

#967 Update anomaly.md
  docs/xdr/features/detect/anomaly.md
Labels: documentation

#957 Doc: redirect the user to SEKOIA.IO docker concentrator doc
  docs/xdr/features/collect/integrations/application/apache.md
  docs/xdr/features/collect/integrations/application/freeradius.md
  docs/xdr/features/collect/integrations/email/fortimail.md
  docs/xdr/features/collect/integrations/endpoint/auditbeat_linux.md
  docs/xdr/features/collect/integrations/endpoint/cybereason_malop_activity.md
  docs/xdr/features/collect/integrations/endpoint/ibm_aix.md
  docs/xdr/features/collect/integrations/endpoint/symantec_epp.md
  docs/xdr/features/collect/integrations/endpoint/trend_micro_deep_security.md
  docs/xdr/features/collect/integrations/endpoint/windows.md
  docs/xdr/features/collect/integrations/network/cisco/cisco_asa.md
  docs/xdr/features/collect/integrations/network/cisco/cisco_meraki_mx.md
  docs/xdr/features/collect/integrations/network/cisco/cisco_nx_os.md
  docs/xdr/features/collect/integrations/network/f5-big-ip.md
  docs/xdr/features/collect/integrations/network/forcepoint_web_gateway.md
  docs/xdr/features/collect/integrations/network/fortigate.md
  docs/xdr/features/collect/integrations/network/fortiproxy.md
  docs/xdr/features/collect/integrations/network/fortiweb.md
  docs/xdr/features/collect/integrations/network/gatewatcher_aioniq.md
  docs/xdr/features/collect/integrations/network/infoblox_ddi.md
  docs/xdr/features/collect/integrations/network/microsoft_always_on_vpn.md
  docs/xdr/features/collect/integrations/network/paloalto.md
  docs/xdr/features/collect/integrations/network/pulse.md
  docs/xdr/features/collect/integrations/network/sonicwall_fw.md
  docs/xdr/features/collect/integrations/network/sophos_fw.md
  docs/xdr/features/collect/integrations/network/watchguard_firebox.md
Labels: enhancement
