Repository SEKOIA-IO/documentation, pull requests merged in 2023-01, with the labels that each got.

#764 Netskope: add documentation
  docs/xdr/features/collect/integrations/cloud_and_saas/netskope_events.md
  mkdocs.yml
Labels: documentation, enhancement

#775 Update FAQ.md
  docs/xdr/FAQ.md
Labels: documentation

#811 Netskope: remove beta notice
  docs/xdr/features/collect/integrations/cloud_and_saas/netskope_events.md
Labels: enhancement

#809 Create xdr_quick_start.md
  docs/assets/operation_center/quick_start/entities.png
  docs/assets/operation_center/quick_start/intakes.png
  docs/assets/operation_center/quick_start/rules.png
  docs/xdr/xdr_quick_start.md
  mkdocs.yml
Labels: documentation
