Repository SEKOIA-IO/documentation, pull requests merged in 2025-02, with the labels that each got.

#2215 MicrosoftOutlook: add the documentation for the automation module
  _shared_content/automate/library/microsoft-outlook.md
  mkdocs.yml
Labels: documentation

#2212 standardising use of quotations in for SOL docs
  docs/xdr/features/investigate/sekoia_operating_language.md
Labels: documentation

#2221 chore: rename the Sesame IT Jizo NDR documentation
  docs/integration/categories/network/sesameit_jizo.md
  mkdocs.yml
Labels: enhancement

#2222 chore: Remove Beta mention from some integrations
  docs/integration/categories/applicative/1password_epm.md
  docs/integration/categories/applicative/systancia_cleanroom.md
  docs/integration/categories/email/mimecast_email_security.md
  docs/integration/categories/endpoint/eset_protect.md
  docs/integration/categories/endpoint/ibm_i.md
  docs/integration/categories/generic/ocsf.md
  docs/integration/categories/iam/azure_key_vault.md
  docs/integration/categories/network/azure_application_gateway.md
  docs/integration/categories/network/juniper_switches.md
  docs/integration/categories/network_security/clavister_ng_fw.md
  docs/integration/categories/network_security/daspren_parad.md
  docs/integration/categories/network_security/fastly_waf.md
  docs/integration/categories/network_security/google_cloud_load_balancing.md
  docs/integration/categories/network_security/olfeo_secure_web_gateway.md
  docs/integration/categories/network_security/thinkst_canary.md
  docs/integration/categories/network_security/ubika_cloud_protector_alerts.md
  docs/integration/categories/network_security/ubika_cloud_protector_traffic.md
Labels: enhancement

#2240 Stormshield: add configuration section
  _shared_content/automate/library/stormshield.md
  docs/assets/playbooks/library/setup/stormshield/Step01.png
  docs/assets/playbooks/library/setup/stormshield/Step02.png
  docs/assets/playbooks/library/setup/stormshield/Step03.png
  docs/assets/playbooks/library/setup/stormshield/Step04.png
  docs/assets/playbooks/library/setup/stormshield/Step05.png
  docs/assets/playbooks/library/setup/stormshield/Step06.png
  docs/assets/playbooks/library/setup/stormshield/Step07.png
Labels: documentation

#2244 MicrosoftSentinel: fix docs
  docs/integration/categories/applicative/microsoft_sentinel.md
Labels: bug

#2245 StormShield: fix doc
  _shared_content/automate/library/stormshield-ses.md
  docs/assets/playbooks/library/setup/stormshield-ses/Step01.png
  docs/assets/playbooks/library/setup/stormshield-ses/Step02.png
  docs/assets/playbooks/library/setup/stormshield-ses/Step03.png
  docs/assets/playbooks/library/setup/stormshield-ses/Step04.png
  docs/assets/playbooks/library/setup/stormshield-ses/Step05.png
  docs/assets/playbooks/library/setup/stormshield-ses/Step06.png
  docs/assets/playbooks/library/setup/stormshield-ses/Step07.png
  docs/assets/playbooks/library/stormshield-ses.png
  mkdocs.yml
Labels: bug

#2248 Stormshield: fix action name
  _shared_content/automate/library/stormshield-ses.md
Labels: bug

#2250 Lockself: fix name and format uuid
  docs/integration/categories/applicative/lockself.md
  mkdocs.yml
Labels: enhancement

#2254 Google: add more details
  docs/integration/categories/applicative/google_reports.md
Labels: enhancement

#2258 Ingestion: add a section about compressed payload in the HTTPS endpoint
  docs/integration/ingestion_methods/https/compression.md
  mkdocs.yml
Labels: enhancement
